spring:
  application:
    name: rnr-app

  datasource:
    url: jdbc:postgresql://postgres:5432/rnr_app
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  devtools:
    restart:
      enabled: true

  security:
    filter:
      chain:
        enabled: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:postgresql://postgres:5432/rnr_app
    user: admin
    password: admin
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: target/schema.sql

  liquibase:
    enabled: false

jwt:
  secret: a-very-strong-secret-key-for-role-n-roll-1234567890!!
  expiration: 900000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        jdbc:
          datasource:
            DriverManagerDataSource: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html